-- Patch: recover missing appointment slot schema for existing DBs
-- Safe to run multiple times (idempotent).

CREATE TABLE IF NOT EXISTS appointment_slots (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_datetime      TIMESTAMP    NOT NULL,
    note               VARCHAR(200),
    created_by_user_id BIGINT       NOT NULL REFERENCES users(id),
    deleted_at         TIMESTAMP,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_appointment_slots_datetime
    ON appointment_slots(slot_datetime);

ALTER TABLE appointments
    ADD COLUMN IF NOT EXISTS slot_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'appointments_slot_id_fkey'
    ) THEN
        ALTER TABLE appointments
            ADD CONSTRAINT appointments_slot_id_fkey
            FOREIGN KEY (slot_id) REFERENCES appointment_slots(id);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_appointments_slot_id
    ON appointments(slot_id);
